# Generated by Django 5.0.2 on 2024-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktorzy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('wiek', models.PositiveSmallIntegerField()),
                ('opis', models.TextField(default='')),
                ('urodzenie', models.DateField(blank=True, null=True)),
                ('imdb_pkts', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
