# Generated by Django 5.0.2 on 2024-03-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_aktorzy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gatunek', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Dramat'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (0, 'Inne')], null=True)),
                ('rezyser', models.CharField(blank=True, max_length=50, null=True)),
                ('film', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmy.film')),
            ],
        ),
    ]
