# Generated by Django 5.0.2 on 2024-03-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='filmy.film')),
            ],
        ),
        migrations.DeleteModel(
            name='Aktorzy',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (3, 'Sci-fi'), (4, 'Dramat'), (2, 'Komedia'), (0, 'Inne')], null=True),
        ),
    ]
